sudo: required
services:
  - docker

before_install:
  - docker build -t cong/hewo -f Dockerfile.dev .

script:
  - docker run cong/hewo npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: "hewo"
  env: "Hewo-env"
  bucket_name: elasticbeanstalk-eu-west-1-088866424314
  bucket_path: "hewo"
  on:
    branch: master
  access_key_id: "$aws_access_key"
  secret_access_key:
    secure: "$aws_secret_key"
